#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPTHAI_CORE_ROOT="${DEPTHAI_CORE_ROOT:-/home/chris4/workspace/from_git/depthai-core}"
DEPTHAI_CORE_BUILD_DIR="${DEPTHAI_CORE_ROOT}/build_no_dcl"
BUILD_DIR="${BUILD_DIR:-${PROJECT_DIR}/build_oak}"

export DEPTHAI_AUTOCALIBRATION=OFF

DEPTHAI_PREFIX_PATH="${DEPTHAI_CORE_BUILD_DIR}"

append_prefix() {
  local p="$1"
  if [ -n "${p}" ] && [ -d "${p}" ]; then
    case ";${DEPTHAI_PREFIX_PATH};" in
      *";${p};"*) ;;
      *) DEPTHAI_PREFIX_PATH="${DEPTHAI_PREFIX_PATH};${p}" ;;
    esac
  fi
}

# Include dependency build/export folders generated by depthai-core FetchContent.
if [ -d "${DEPTHAI_CORE_BUILD_DIR}/_deps" ]; then
  while IFS= read -r dep_build_dir; do
    append_prefix "${dep_build_dir}"
  done < <(find "${DEPTHAI_CORE_BUILD_DIR}/_deps" -mindepth 1 -maxdepth 1 -type d -name '*-build' | sort -u)

  while IFS= read -r cfg; do
    cfg_dir="$(dirname "${cfg}")"
    append_prefix "${cfg_dir}"

    # Convert .../lib/cmake/pkg/pkgConfig.cmake -> ... prefix.
    case "${cfg_dir}" in
      */lib/cmake/*)
        append_prefix "${cfg_dir%%/lib/cmake/*}"
        ;;
      */share/*)
        append_prefix "${cfg_dir%%/share/*}"
        ;;
      */cmake/*)
        append_prefix "${cfg_dir%%/cmake/*}"
        ;;
    esac
  done < <(find "${DEPTHAI_CORE_BUILD_DIR}/_deps" -type f \( -name '*Config.cmake' -o -name '*-config.cmake' \) | sort -u)
fi

if [ -d "${DEPTHAI_CORE_BUILD_DIR}/vcpkg_installed" ]; then
  while IFS= read -r vcpkg_prefix; do
    append_prefix "${vcpkg_prefix}"
  done < <(find "${DEPTHAI_CORE_BUILD_DIR}/vcpkg_installed" -mindepth 1 -maxdepth 1 -type d | sort -u)
fi

# if [ -n "${CONDA_PREFIX:-}" ]; then
#   DEPTHAI_PREFIX_PATH="${CONDA_PREFIX};${DEPTHAI_PREFIX_PATH}"
# fi

# Preserve any caller-provided extra prefix entries.
if [ -n "${CMAKE_PREFIX_PATH:-}" ]; then
  DEPTHAI_PREFIX_PATH="${CMAKE_PREFIX_PATH};${DEPTHAI_PREFIX_PATH}"
fi

echo "DEPTHAI_PREFIX_PATH=${DEPTHAI_PREFIX_PATH}"

cmake -S . -B build_oak \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_OAK_RGBD_TARGET=ON \
  -DBUILD_INDEMIND_TARGET=OFF \
  -DDEPTHAI_CORE_ROOT="${DEPTHAI_CORE_ROOT}" \
  -DDEPTHAI_CORE_BUILD_DIR="${DEPTHAI_CORE_BUILD_DIR}" \
  -DCMAKE_PREFIX_PATH="${DEPTHAI_PREFIX_PATH}" \
  -DOpenCV_DIR=/opt/opencv4-cuda/lib/cmake/opencv4 \
  -DBoost_NO_BOOST_CMAKE=ON \
  -DBoost_NO_SYSTEM_PATHS=OFF \
  -DBOOST_ROOT=/usr \
  -DBoost_INCLUDE_DIR=/usr/include \
  -DBoost_LIBRARY_DIR_RELEASE=/usr/lib/x86_64-linux-gnu

cmake --build "${BUILD_DIR}" --parallel

echo
echo "Built: ${PROJECT_DIR}/build_agent_out/yolo_pose_oak_rgbd"
echo "Run:   DEPTHAI_AUTOCALIBRATION=OFF ${PROJECT_DIR}/build_agent_out/yolo_pose_oak_rgbd models/yolov8n-pose-640.onnx"
