#!/bin/bash
#
# Install OpenCV with CUDA support to a separate directory
# This will NOT affect your existing OpenCV 3.4.3 installation
#
# Installation path: /opt/opencv4-cuda
#

set -e

# Configuration
OPENCV_VERSION="4.8.0"
INSTALL_PREFIX="/opt/opencv4-cuda"
BUILD_DIR="$HOME/opencv_cuda_build"
CUDA_ARCH="8.6"  # Adjust for your GPU (e.g., 7.5 for RTX 2080, 8.6 for RTX 3080/3090)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}  OpenCV ${OPENCV_VERSION} with CUDA Installation${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""
echo "This script will:"
echo "  1. Download OpenCV ${OPENCV_VERSION} source code"
echo "  2. Compile with CUDA support"
echo "  3. Install to: ${INSTALL_PREFIX}"
echo ""
echo -e "${YELLOW}Your existing OpenCV 3.4.3 will NOT be affected!${NC}"
echo ""

# Detect GPU architecture
echo "Detecting GPU architecture..."
if command -v nvidia-smi &> /dev/null; then
    GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -n1)
    echo -e "Found GPU: ${GREEN}${GPU_NAME}${NC}"

    # Auto-detect CUDA architecture based on GPU name
    case "$GPU_NAME" in
        *"RTX 40"*|*"RTX 4090"*|*"RTX 4080"*|*"RTX 4070"*|*"RTX 4060"*)
            CUDA_ARCH="8.9"
            ;;
        *"RTX 30"*|*"RTX 3090"*|*"RTX 3080"*|*"RTX 3070"*|*"RTX 3060"*|*"A100"*|*"A10"*)
            CUDA_ARCH="8.6"
            ;;
        *"RTX 20"*|*"RTX 2080"*|*"RTX 2070"*|*"RTX 2060"*|*"T4"*)
            CUDA_ARCH="7.5"
            ;;
        *"GTX 1080"*|*"GTX 1070"*|*"GTX 1060"*|*"P100"*|*"P40"*)
            CUDA_ARCH="6.1"
            ;;
        *"GTX 1050"*|*"GTX 1030"*)
            CUDA_ARCH="6.1"
            ;;
        *)
            echo -e "${YELLOW}Could not auto-detect GPU architecture, using ${CUDA_ARCH}${NC}"
            ;;
    esac
    echo -e "Using CUDA architecture: ${GREEN}${CUDA_ARCH}${NC}"
else
    echo -e "${RED}nvidia-smi not found, cannot detect GPU${NC}"
    exit 1
fi

echo ""
read -p "Continue with installation? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation cancelled."
    exit 0
fi

# Install dependencies
echo ""
echo -e "${GREEN}[1/5] Installing dependencies...${NC}"
sudo apt-get update
sudo apt-get install -y \
    build-essential cmake git pkg-config \
    libgtk-3-dev libavcodec-dev libavformat-dev libswscale-dev \
    libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev \
    libdc1394-dev libv4l-dev v4l-utils \
    libxvidcore-dev libx264-dev \
    libatlas-base-dev gfortran \
    python3-dev python3-numpy

# Create build directory
echo ""
echo -e "${GREEN}[2/5] Creating build directory...${NC}"
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

# Download OpenCV
echo ""
echo -e "${GREEN}[3/5] Downloading OpenCV ${OPENCV_VERSION}...${NC}"
if [ ! -d "opencv" ]; then
    git clone --depth 1 --branch ${OPENCV_VERSION} https://github.com/opencv/opencv.git
fi

if [ ! -d "opencv_contrib" ]; then
    git clone --depth 1 --branch ${OPENCV_VERSION} https://github.com/opencv/opencv_contrib.git
fi

# Configure
echo ""
echo -e "${GREEN}[4/5] Configuring OpenCV with CUDA...${NC}"
cd opencv
mkdir -p build
cd build

cmake \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
    -D OPENCV_EXTRA_MODULES_PATH=${BUILD_DIR}/opencv_contrib/modules \
    -D WITH_CUDA=ON \
    -D CUDA_ARCH_BIN=${CUDA_ARCH} \
    -D CUDA_ARCH_PTR="" \
    -D ENABLE_FAST_MATH=ON \
    -D CUDA_FAST_MATH=ON \
    -D WITH_CUBLAS=ON \
    -D WITH_CUDNN=ON \
    -D OPENCV_DNN_CUDA=ON \
    -D BUILD_opencv_cudastereo=ON \
    -D BUILD_opencv_cudaimgproc=ON \
    -D BUILD_opencv_cudafilters=ON \
    -D BUILD_opencv_cudawarping=ON \
    -D WITH_TBB=ON \
    -D WITH_V4L=ON \
    -D WITH_OPENGL=ON \
    -D BUILD_EXAMPLES=OFF \
    -D BUILD_TESTS=OFF \
    -D BUILD_PERF_TESTS=OFF \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_opencv_python3=OFF \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    ..

# Build
echo ""
echo -e "${GREEN}[5/5] Building OpenCV (this may take 30-60 minutes)...${NC}"
echo "Using $(nproc) CPU cores"
make -j$(nproc)

# Install
echo ""
echo -e "${GREEN}Installing to ${INSTALL_PREFIX}...${NC}"
sudo mkdir -p ${INSTALL_PREFIX}
sudo make install

# Create configuration file for this project
echo ""
echo -e "${GREEN}Creating configuration...${NC}"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cat > "${SCRIPT_DIR}/opencv_cuda_path.cmake" << EOF
# OpenCV CUDA installation path
# Auto-generated by install_opencv_cuda.sh

set(OpenCV_CUDA_DIR "${INSTALL_PREFIX}")
set(OpenCV_DIR "${INSTALL_PREFIX}/lib/cmake/opencv4")
EOF

echo ""
echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}  Installation Complete!${NC}"
echo -e "${GREEN}======================================${NC}"
echo ""
echo "OpenCV ${OPENCV_VERSION} with CUDA installed to: ${INSTALL_PREFIX}"
echo ""
echo "To use this OpenCV version in your project, set:"
echo "  export OpenCV_DIR=${INSTALL_PREFIX}/lib/cmake/opencv4"
echo ""
echo "Or rebuild the gpu_depth_demo:"
echo "  cd ${SCRIPT_DIR}"
echo "  rm -rf build && ./build.sh"
echo ""
echo -e "${YELLOW}Your system OpenCV 3.4.3 is unchanged!${NC}"
echo ""
